### ISSUE TITLE
ERROR ~ Error executing process > 'pipeline:report' when sample names are numbers only

### ISSUE THREAD

**Issue by rrdavis77** [epi2me-labs/wf-artic#101]
### Operating System

Ubuntu 22.04

### Workflow Version

v0.3.32

### Workflow Execution

Command line

### CLI command run

`NXF_VER=23.04.2 nextflow run epi2me-labs/wf-artic   --fastq /home/ryan/NGS_Data/Promethion_data/ --report_depth 20  --scheme_name SARS-CoV-2   --scheme_version Midnight-ONT/V3   --out_dir /home/ryan/NGS_Data/midnight_test_run/wf-artic-results_72hr_correct_medaka2/   --sample_sheet samplesheet_nanopore_wf-artic-10-29-23.csv   -w /home/ryan/NGS_Data/midnight_test_run/wf-artic-results_72hrcorrect_medaka2/workspace  --medaka_variant_model r1041_e82_400bps_sup_variant_g615  -resume --update_data false --artic_threads 15  -c config_wfartic.cfg --basecaller_cfg dna_r10.4.1_e8.2_400bps_sup@v3.5.2`

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

The entire pipeline will run succesfully until it tries to generate the final html report.  Most of my sample names are only digits.  And it throws an error such as:

`ValueError: failed to validate Panel(id='1130', ...).title: expected a value of type str, got 500125050 of type int64`

 
If I add a string of text to my sample names then the pipeline completes succesfully.  This error will most likely only happen with sample names that are digits.

### Relevant log output

```shell
[b7/094bc5] process > validate_sample_sheet   [100%] 1 of 1 ✔
[cf/44fad9] process > fastcat (87)            [100%] 96 of 96 ✔
[64/0c8aec] process > pipeline:getVersions    [100%] 1 of 1 ✔
[9a/ea0373] process > pipeline:getParams      [100%] 1 of 1 ✔
[91/2683d1] process > pipeline:runArtic (96)  [100%] 96 of 96 ✔
[e2/553208] process > pipeline:combineDepth   [100%] 1 of 1 ✔
[d2/a9d82f] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[99/8e81ec] process > pipeline:allVariants    [100%] 1 of 1 ✔
[ee/84b27d] process > pipeline:prep_nextclade [100%] 1 of 1 ✔
[66/449f54] process > pipeline:nextclade      [100%] 1 of 1 ✔
[66/31ad9e] process > pipeline:pangolin       [100%] 1 of 1 ✔
[7e/7b6a69] process > pipeline:report         [100%] 1 of 1, failed: 1 ✘
[e1/beea7b] process > output (383)            [ 99%] 389 of 391
ERROR ~ Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo '[
      {
          "barcode": "barcode08",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125050",
          "alias": "500125050"
      },
      {
          "barcode": "barcode01",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "NTC_A1",
          "alias": "NTC_A1"
      },
      {
          "barcode": "barcode16",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125058",
          "alias": "500125058"
      },
      {
          "barcode": "barcode20",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125062",
          "alias": "500125062"
      },
      {
          "barcode": "barcode17",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125059",
          "alias": "500125059"
      },
      {
          "barcode": "barcode10",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125052",
          "alias": "500125052"
      },
      {
          "barcode": "barcode26",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125068",
          "alias": "500125068"
      },
      {
          "barcode": "barcode15",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125057",
          "alias": "500125057"
      },
      {
          "barcode": "barcode21",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125063",
          "alias": "500125063"
      },
      {
          "barcode": "barcode18",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125060",
          "alias": "500125060"
      },
      {
          "barcode": "barcode04",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125046",
          "alias": "500125046"
      },
      {
          "barcode": "barcode03",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125045",
          "alias": "500125045"
      },
      {
          "barcode": "barcode19",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125061",
          "alias": "500125061"
      },
      {
          "barcode": "barcode25",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125067",
          "alias": "500125067"
      },
      {
          "barcode": "barcode29",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125071",
          "alias": "500125071"
      },
      {
          "barcode": "barcode14",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125056",
          "alias": "500125056"
      },
      {
          "barcode": "barcode06",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125048",
          "alias": "500125048"
      },
      {
          "barcode": "barcode22",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125064",
          "alias": "500125064"
      },
      {
          "barcode": "barcode31",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125073",
          "alias": "500125073"
      },
      {
          "barcode": "barcode05",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125047",
          "alias": "500125047"
      },
      {
          "barcode": "barcode27",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125069",
          "alias": "500125069"
      },
      {
          "barcode": "barcode23",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125065",
          "alias": "500125065"
      },
      {
          "barcode": "barcode12",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125054",
          "alias": "500125054"
      },
      {
          "barcode": "barcode02",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125044",
          "alias": "500125044"
      },
      {
          "barcode": "barcode81",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125122",
          "alias": "500125122"
      },
      {
          "barcode": "barcode30",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125072",
          "alias": "500125072"
      },
      {
          "barcode": "barcode13",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125055",
          "alias": "500125055"
      },
      {
          "barcode": "barcode07",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125049",
          "alias": "500125049"
      },
      {
          "barcode": "barcode33",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125075",
          "alias": "500125075"
      },
      {
          "barcode": "barcode48",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "NTC_H6",
          "alias": "NTC_H6"
      },
      {
          "barcode": "barcode32",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125074",
          "alias": "500125074"
      },
      {
          "barcode": "barcode28",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125070",
          "alias": "500125070"
      },
      {
          "barcode": "barcode49",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "NTC_A7",
          "alias": "NTC_A7"
      },
      {
          "barcode": "barcode09",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125051",
          "alias": "500125051"
      },
      {
          "barcode": "barcode24",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125066",
          "alias": "500125066"
      },
      {
          "barcode": "barcode35",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125077",
          "alias": "500125077"
      },
      {
          "barcode": "barcode42",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125084",
          "alias": "500125084"
      },
      {
          "barcode": "barcode36",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125078",
          "alias": "500125078"
      },
      {
          "barcode": "barcode50",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125091",
          "alias": "500125091"
      },
      {
          "barcode": "barcode38",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125080",
          "alias": "500125080"
      },
      {
          "barcode": "barcode45",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125088",
          "alias": "500125088"
      },
      {
          "barcode": "barcode34",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125076",
          "alias": "500125076"
      },
      {
          "barcode": "barcode11",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125053",
          "alias": "500125053"
      },
      {
          "barcode": "barcode37",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125079",
          "alias": "500125079"
      },
      {
          "barcode": "barcode43",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125086",
          "alias": "500125086"
      },
      {
          "barcode": "barcode52",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125093",
          "alias": "500125093"
      },
      {
          "barcode": "barcode57",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125098",
          "alias": "500125098"
      },
      {
          "barcode": "barcode53",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125094",
          "alias": "500125094"
      },
      {
          "barcode": "barcode44",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125087",
          "alias": "500125087"
      },
      {
          "barcode": "barcode41",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125083",
          "alias": "500125083"
      },
      {
          "barcode": "barcode54",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125095",
          "alias": "500125095"
      },
      {
          "barcode": "barcode47",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125090",
          "alias": "500125090"
      },
      {
          "barcode": "barcode63",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125104",
          "alias": "500125104"
      },
      {
          "barcode": "barcode62",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125103",
          "alias": "500125103"
      },
      {
          "barcode": "barcode46",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125089",
          "alias": "500125089"
      },
      {
          "barcode": "barcode58",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125099",
          "alias": "500125099"
      },
      {
          "barcode": "barcode61",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125102",
          "alias": "500125102"
      },
      {
          "barcode": "barcode65",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125106",
          "alias": "500125106"
      },
      {
          "barcode": "barcode66",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125107",
          "alias": "500125107"
      },
      {
          "barcode": "barcode39",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125081",
          "alias": "500125081"
      },
      {
          "barcode": "barcode78",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125119",
          "alias": "500125119"
      },
      {
          "barcode": "barcode77",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125118",
          "alias": "500125118"
      },
      {
          "barcode": "barcode51",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125092",
          "alias": "500125092"
      },
      {
          "barcode": "barcode59",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125100",
          "alias": "500125100"
      },
      {
          "barcode": "barcode64",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125105",
          "alias": "500125105"
      },
      {
          "barcode": "barcode74",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125115",
          "alias": "500125115"
      },
      {
          "barcode": "barcode85",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125126",
          "alias": "500125126"
      },
      {
          "barcode": "barcode71",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125112",
          "alias": "500125112"
      },
      {
          "barcode": "barcode40",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125082",
          "alias": "500125082"
      },
      {
          "barcode": "barcode55",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125096",
          "alias": "500125096"
      },
      {
          "barcode": "barcode56",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125097",
          "alias": "500125097"
      },
      {
          "barcode": "barcode70",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125111",
          "alias": "500125111"
      },
      {
          "barcode": "barcode67",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125108",
          "alias": "500125108"
      },
      {
          "barcode": "barcode76",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125117",
          "alias": "500125117"
      },
      {
          "barcode": "barcode73",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125114",
          "alias": "500125114"
      },
      {
          "barcode": "barcode96",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "PC",
          "alias": "PC"
      },
      {
          "barcode": "barcode79",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125120",
          "alias": "500125120"
      },
      {
          "barcode": "barcode72",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125113",
          "alias": "500125113"
      },
      {
          "barcode": "barcode60",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125101",
          "alias": "500125101"
      },
      {
          "barcode": "barcode68",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125109",
          "alias": "500125109"
      },
      {
          "barcode": "barcode94",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "NTC_F12",
          "alias": "NTC_F12"
      },
      {
          "barcode": "barcode95",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "NTC_G12",
          "alias": "NTC_G12"
      },
      {
          "barcode": "barcode69",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125110",
          "alias": "500125110"
      },
      {
          "barcode": "barcode82",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125123",
          "alias": "500125123"
      },
      {
          "barcode": "barcode80",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125121",
          "alias": "500125121"
      },
      {
          "barcode": "barcode75",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125116",
          "alias": "500125116"
      },
      {
          "barcode": "barcode83",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125124",
          "alias": "500125124"
      },
      {
          "barcode": "barcode93",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500122544",
          "alias": "500122544"
      },
      {
          "barcode": "barcode89",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125130",
          "alias": "500125130"
      },
      {
          "barcode": "barcode84",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125125",
          "alias": "500125125"
      },
      {
          "barcode": "barcode86",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125127",
          "alias": "500125127"
      },
      {
          "barcode": "barcode90",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125131",
          "alias": "500125131"
      },
      {
          "barcode": "barcode88",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125129",
          "alias": "500125129"
      },
      {
          "barcode": "barcode91",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125132",
          "alias": "500125132"
      },
      {
          "barcode": "barcode92",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125133",
          "alias": "500125133"
      },
      {
          "barcode": "barcode87",
          "type": "test_sample",
          "run_ids": [
              "a15e2b6ec6d60c4e5dc8821c5596a3c655ca7df1"
          ],
          "sample_id": "500125128",
          "alias": "500125128"
      }
  ]' > metadata.json
      workflow-glue report         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv           --nextclade nextclade.json         --nextclade_errors consensus.errors.csv         --revision master         --commit 443c9f0e1bcf2188b955af68183a7f18e6477f7b         --min_len 150         --max_len 1200         --report_depth 20         --depths depth_stats/*         --fastcat_stats per_read_stats/*         --bcftools_stats vcf_stats/*          --versions versions         --params params.json         --consensus_fasta consensus_fasta         --metadata metadata.json

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  --pangolin pangolin.csv
  --nextclade nextclade.json
  /home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/report.py:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  [00:33:00 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/ryan/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/ryan/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/home/ryan/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/report.py", line 113, in main
      tabs[sample_id] = Panel(child=grid, title=sample_id)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/model/model.py", line 128, in __init__
      super().__init__(**kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/has_props.py", line 206, in __init__
      setattr(self, name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/has_props.py", line 230, in __setattr__
      return super().__setattr__(name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 283, in __set__
      value = self.property.prepare_value(obj, self.name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/property/bases.py", line 365, in prepare_value
      raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
  ValueError: failed to validate Panel(id='1130', ...).title: expected a value of type str, got 500125050 of type int64

Work dir:
  /home/ryan/NGS_Data/midnight_test_run/wf-artic-results_72hrcorrect_medaka2/workspace/7e/7b6a699b807cd35ba16d4bedf39ad8

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by cjalder** [comment]
Hi @rrdavis77, thanks for highlighting the issue. We are aware of the problem with numerical sample names and its on our list of updates for the workflow.

**Comment by ammaraziz** [comment]
In the process of updating the pipeline to the latest version I have come across this bug. Unfortunately the unique IDs we use are all numbers. This bug persists all the way from version 3.24 to 3.33. 

My apologies for bugging @cjalder but it's really a huge issue for us currently.

**Comment by cjalder** [comment]
Apologies @ammaraziz - Like stated above the work is on our forecast for future work. I will see if it can be expedited.

**Comment by ammaraziz** [comment]
Thank you @cjalder for your understanding.

I have identified the issue and will submit a pull request. 

Thanks again,

Ammar
