### ISSUE TITLE
Invalid output definition when I try to run test data

### ISSUE THREAD

**Issue by MauriAndresMU1313** [epi2me-labs/wf-artic#111]
### Operating System

Ubuntu 22.04

### Workflow Version

v3.10.0

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-artic --fastq ./wf-artic-demo/fastq/ -profile standard

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

I'm trying to run the test data after downloading the test dataset provided by [https://github.com/epi2me-labs/wf-artic](wf-artic)
I have Docker installed (version 26.1.4) and my Java version:
```
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
```
My ```wf-artic-demo``` directory looks like this:
```
fastq  md5sums.txt  nextflow.config  output  README  sample_sheet.csv  work
```
So far, when I tried to run this test line:
```
nextflow run epi2me-labs/wf-artic --fastq ./wf-artic-demo/fastq/ -profile standard
```
I got the following error:
```
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script_e4f9eb14011d9e79: 638: Invalid output definition @ line 638, column 5.
       output(results)
       ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:980)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:572)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:585)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:639)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:643)
	at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:175)
	... 6 common frames omitted
```
I could not figure out what is the issue.

### Relevant log output

```shell
Jun-17 19:51:27.779 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-artic --fastq ./wf-artic-demo/fastq/ -profile standard
Jun-17 19:51:27.878 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.2
Jun-17 19:51:27.912 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/mmora30/.nextflow/plugins; core-plugins: nf-amazon@2.5.2,nf-azure@1.6.0,nf-cloudcache@0.4.1,nf-codecommit@0.2.0,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2,nf-tower@1.9.1,nf-wave@1.4.2
Jun-17 19:51:27.932 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-17 19:51:27.934 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-17 19:51:27.939 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.10.0 in 'deployment' mode
Jun-17 19:51:27.965 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jun-17 19:51:27.990 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/mmora30/.nextflow/scm
Jun-17 19:51:28.992 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-artic.git
Jun-17 19:51:29.035 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Jun-17 19:51:29.048 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-artic.git
Jun-17 19:51:29.772 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/nextflow.config
Jun-17 19:51:29.773 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/mmora30/workspace/nextflow_pipelines/wf-artic-demo/nextflow.config
Jun-17 19:51:29.775 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/nextflow.config
Jun-17 19:51:29.776 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/mmora30/workspace/nextflow_pipelines/wf-artic-demo/nextflow.config
Jun-17 19:51:29.785 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/mmora30/.nextflow/secrets/store.json
Jun-17 19:51:29.789 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@392781e] - activable => nextflow.secret.LocalSecretsProvider@392781e
Jun-17 19:51:29.803 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-17 19:51:30.020 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-17 19:51:30.081 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Jun-17 19:51:30.083 [main] DEBUG nextflow.cli.CmdRun - Launching `https://github.com/epi2me-labs/wf-artic` [cranky_meninsky] DSL2 - revision: cf4041c563 [master]
Jun-17 19:51:30.085 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-17 19:51:30.085 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jun-17 19:51:30.166 [main] DEBUG nextflow.Session - Session UUID: 6970c700-3c0d-496c-95c6-97e001be947d
Jun-17 19:51:30.167 [main] DEBUG nextflow.Session - Run name: cranky_meninsky
Jun-17 19:51:30.168 [main] DEBUG nextflow.Session - Executor pool size: 24
Jun-17 19:51:30.180 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Jun-17 19:51:30.187 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=72; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jun-17 19:51:30.213 [main] DEBUG nextflow.cli.CmdRun -
  Version: 24.04.2 build 5914
  Created: 29-05-2024 06:19 UTC
  System: Linux 5.15.0-112-generic
  Runtime: Groovy 4.0.21 on OpenJDK 64-Bit Server VM 11.0.23+9-post-Ubuntu-1ubuntu122.04.1
  Encoding: UTF-8 (UTF-8)
  Process: 123242@medina-lab [127.0.1.1]
  CPUs: 24 - Mem: 122.8 GB (95 GB) - Swap: 8 GB (8 GB)
Jun-17 19:51:30.243 [main] DEBUG nextflow.Session - Work-dir: /home/mmora30/workspace/nextflow_pipelines/wf-artic-demo/work [ext2/ext3]
Jun-17 19:51:30.307 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-17 19:51:30.332 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-17 19:51:30.444 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-17 19:51:30.461 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 25; maxThreads: 1000
Jun-17 19:51:30.548 [main] DEBUG nextflow.Session - Session start
Jun-17 19:51:30.551 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow started -- trace file: /home/mmora30/workspace/nextflow_pipelines/wf-artic-demo/output/execution/trace.txt
Jun-17 19:51:30.560 [main] DEBUG nextflow.Session - Using default localLib path: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/lib
Jun-17 19:51:30.566 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/lib
Jun-17 19:51:30.566 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/lib/nfcore_external_java_deps.jar
Jun-17 19:51:31.985 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
Jun-17 19:51:31.994 [main] ERROR nextflow.cli.Launcher - Script compilation error
- file : /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/main.nf
- cause: Invalid output definition @ line 638, column 5.
       output(results)
       ^

1 error

nextflow.exception.ScriptCompilationException: Script compilation error
- file : /home/mmora30/.nextflow/assets/epi2me-labs/wf-artic/main.nf
- cause: Invalid output definition @ line 638, column 5.
       output(results)
       ^

1 error

	at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:196)
	at nextflow.script.ScriptParser.parse(ScriptParser.groovy:206)
	at nextflow.script.ScriptRunner.parseScript(ScriptRunner.groovy:229)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:136)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script_e4f9eb14011d9e79: 638: Invalid output definition @ line 638, column 5.
       output(results)
       ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:980)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:572)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:585)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:639)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:643)
	at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:175)
	... 6 common frames omitted
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by julibeg** [comment]
Hi @MauriAndresMU1313, this issue is due to an incompatibility of a new feature introduced in the latest Nextflow version with some of our workflows. It will be fixed in the next wf-artic release. In the meantime, you can run the workflow with an older version of Nextflow as follows

```
NXF_VER=23.10.1 nextflow run epi2me-labs/wf-artic --fastq ./wf-artic-demo/fastq/ -profile standard
```

Many thanks for your patience!
