### ISSUE TITLE
Cannot import pyabpoa without Internet - medaka doesn’t make a sequence consensus

### ISSUE THREAD

**Issue by evfratov** [epi2me-labs/wf-artic#116]
### Ask away!

Linux (both normal Ubuntu and WSL Ubuntu) wf-artic fails on demo data without network, argument '--update_dala false' does not help - consensus file contains empty sequences. barcodeNN.artic.log.txt contains this error (49 as an example):

```
[M::main] CMD: minimap2 -a -x map-ont -t 4 SARS-CoV-2/Midnight-ONT/V3/SARS-CoV-2.reference.fasta barcode49_barcode49.fastq
[M::main] Real time: 0.701 sec; CPU: 1.721 sec; Peak RSS: 0.048 GB
Cannot import pyabpoa, some features may not be available.
Failed to interpret 'dna_r9.4.1_e8_hac@v3.3:consensus' as a basecaller model.
Traceback (most recent call last):
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/medaka.py", line 36, in __call__
    model_fp = medaka.models.resolve_model(val)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/models.py", line 46, in resolve_model
    raise ValueError(
ValueError: Model dna_r9.4.1_e8_hac@v3.3:consensus is not a known model or existant file.
```

fail for current wf-artic 1.2.2, both 1.2.1 and 1.2.0
fail for current Nextflow 24.10.2, both 23.10.4 and 22.10.7
manual installation python3-puabpoa is useless

And with the network everything is ok except some probability of fail due to improper network stability.

What is wrong? Why a critical network dependency isn't documented?

**Comment by ammaraziz** [comment]
I have this same issue. This is related to or caused by updating the `ontresearch/wf-artic` docker image.

**Comment by ammaraziz** [comment]
I also get this error:

```
[M::mm_idx_gen::0.002*1.90] collected minimizers
[M::mm_idx_gen::0.004*2.64] sorted minimizers
[M::main::0.004*2.63] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*2.45] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*2.40] distinct minimizers: 5587 (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332; total length: 29903
[M::worker_pipeline::12.006*2.60] mapped 168736 sequences
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -a -x map-ont -t 4 SARS-CoV-2/ARTIC-ONT/V5.2/SARS-CoV-2.reference.fasta 24188419_24188419.fastq
[M::main] Real time: 12.007 sec; CPU: 31.221 sec; Peak RSS: 0.275 GB
Cannot import pyabpoa, some features may not be available.
Failed to interpret 'dna_r10.4.1_e8.2_400bps_hac@v4.3.0:consensus' as a basecaller model.
Traceback (most recent call last):
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/medaka.py", line 36, in __call__
    model_fp = medaka.models.resolve_model(val)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packag+ mock_artic
+ echo 'Mocking artic results'
Mocking artic results
```

The error regarding `pyabopoa` is actually a warning and not relevant here. The issue is the model name of `dna_r10.4.1_e8.2_400bps_hac@v4.3.0:consensus`. I am not sure why `:consensus` is being appended to the name...

**Comment by ammaraziz** [comment]
I think the issue stems from the auto model selector, however it works, messes with the model name. You can fix this by manually specifying the model using `--override_basecaller_cfg`.

**Comment by evfratov** [comment]
> I think the issue stems from the auto model selector, however it works, messes with the model name. You can fix this by manually specifying the model using `--override_basecaller_cfg`.

Direct specification of a basecalling model doesn't give any effect on the consensus assembly:


nextflow run epi2me-labs/wf-artic --fastq wf-artic-demo/fastq --update_data false --out_dir output-def-net _with network_ **work**
nextflow run epi2me-labs/wf-artic --fastq wf-artic-demo/fastq --update_data false --out_dir output-def-nonet _no network_ **fail**
nextflow run epi2me-labs/wf-artic --fastq wf-artic-demo/fastq --update_data false --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_sup@v4.3.0 --out_dir output-cfg10-nonet _no network_ **fail**
nextflow run epi2me-labs/wf-artic --fastq wf-artic-demo/fastq --update_data false --override_basecaller_cfg dna_r9.4.1_e8_hac@v3.3 --out_dir output-cfg9-nonet _no network_ **fail**

**Comment by ammaraziz** [comment]
You are correct, it's not the model name but the lack of internet connection. The models are not available in the docker image, leading to the errors we are seeing.

We are facing the same issue, which is now ~6 months old:
https://github.com/epi2me-labs/wf-artic/issues/95

A hacky solution was posted by another user in the above issue. I'm testing it out today.

**Comment by evfratov** [comment]
> You are correct, it's not the model name but the lack of internet connection. The models are not available in the docker image, leading to the errors we are seeing.
> 
> We are facing the same issue, which is now ~6 months old: [#95](https://github.com/epi2me-labs/wf-artic/issues/95)
> 
> A hacky solution was posted by another user in the above issue. I'm testing it out today.

This pipeline can be run without the networn dependency only after heavy downgrade - both for ARTIC and for Nextflow

NXF_VER=23.10.0 nextflow run epi2me-labs/wf-artic -r v0.3.31 --update_data false --scheme_name 'SARS-CoV-2' --scheme_version 'ARTIC/V3' --fastq <folder-in> --out_dir <folder-out>

**Comment by Rohit-Satyam** [comment]
I am facing the similar issue. Getting the same error

```
+ READFILE=DAMAM_5-2_barcode35_DAMAM_5-2_barcode35.fastq
+ artic minion --medaka --normalise 200 --threads 20 --read-file DAMAM_5-2_barcode35_DAMAM_5-2_barcode35.fastq --medaka-model dna_r10.4.1_e8.2_400bps_sup@v4.3.0:consensus --scheme-directory SARS-CoV-2 --scheme-version ARTIC/V4.1 --max-softclip-length 0 SARS-CoV-2 DAMAM_5-2_barcode35
[M::mm_idx_gen::0.001*11.76] collected minimizers
[M::mm_idx_gen::0.003*11.51] sorted minimizers
[M::main::0.003*11.43] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.003*10.41] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.003*9.94] distinct minimizers: 5587 (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332; total length: 29903
[M::worker_pipeline::0.038*1.84] mapped 3900 sequences
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -a -x map-ont -t 20 SARS-CoV-2/ARTIC/V4.1/SARS-CoV-2.reference.fasta DAMAM_5-2_barcode35_DAMAM_5-2_barcode35.fastq
[M::main] Real time: 0.040 sec; CPU: 0.071 sec; Peak RSS: 0.009 GB
Cannot import pyabpoa, some features may not be available.
Failed to interpret 'dna_r10.4.1_e8.2_400bps_sup@v4.3.0:consensus' as a basecaller model.
Traceback (most recent call last):
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/medaka.py", line 36, in __call__
    model_fp = medaka.models.resolve_model(val)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/models.py", line 46, in resolve_model
    raise ValueError(
ValueError: Model dna_r10.4.1_e8.2_400bps_sup@v4.3.0:consensus is not a known model or existant file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/custflow/epi2meuser/conda/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/medaka.py", line 830, in main
    args = parser.parse_args()
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1988, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1159, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/medaka/medaka.py", line 39, in __call__
    raise RuntimeError(msg.format(self.dest, str(e)))
RuntimeError: Error validating model from '--model' argument: Model dna_r10.4.1_e8.2_400bps_sup@v4.3.0:consensus is not a known model or existant file..
/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/clint/textui/prompt.py:68: SyntaxWarning: "is not" with a literal. Did you mean "!="?

```
