### ISSUE TITLE
error while executing pipeline with custom_scheme parameter

### ISSUE THREAD

**Issue by Wanamalauasha** [epi2me-labs/wf-artic#48]
Hi,

I run into a problem while running the latest version of the workflow (v0.3.13) with the `--custom_scheme` parameter. It just displays the parameters used in the pipeline followed by the following. The error says "No such variable: c_purple". 

The nextflow log seems to point out that the variable c_purple doesn't exist (sorry if this doesn't make sense, Groovy errors are hard to get):

`Apr-21 15:20:28.134 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: c_purple for class: nextflow.script.WorkflowBinding
Apr-21 15:20:28.145 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: c_purple for class: nextflow.script.WorkflowBinding
        at groovy.lang.Binding.getVariable(Binding.java:56)
        at nextflow.script.WorkflowBinding.getVariable(WorkflowBinding.groovy:132)
        at groovy.lang.Binding.getProperty(Binding.java:116)
        at nextflow.script.WorkflowBinding.getProperty(WorkflowBinding.groovy:121)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:320)
        at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:310)
        at groovy.lang.Closure.getProperty(Closure.java:296)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at Script_e058cee8$_runScript_closure20$_closure59.doCall(Script_e058cee8:602)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
        at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
        at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
        at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:191)
        at nextflow.script.BaseScript.run(BaseScript.groovy:200)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
        at nextflow.cli.Launcher.run(Launcher.groovy:480)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)`

I found this using a code similar to this:

`nextflow run epi2me-labs/wf-artic -profile docker -c docker.config --fastq /absolute/path/to/Run12/run12/run12/fastq_pass/ --scheme_name SARS-CoV-2 --custom_scheme /absolute/path/to/custom_scheme_folder/ --min_len 150 --max_len 1200 --sample_sheet /absolute/path/to/sample_sheet_wf-artic-run12.csv --medaka_model r941_min_fast_variant_g507 --out_dir /absolute/path/to/output_wf-artic --report_depth 100 --report_name Run12`

Any hint will be appreciated! thanks :)

**Comment by mattdmem** [comment]
Hello

This is my fault.

These logging colors should have been outside the if statement.

https://github.com/epi2me-labs/wf-artic/blob/fe094ad94586b5778c1cfa9431b53d28fbf414c7/main.nf#L521

If your comfortable pulling the repo and editing the code then move lines 521-524  up to 517.

I'll release a new version to fix asap.

Thanks

Matt

**Comment by Wanamalauasha** [comment]
Hi @mattdmem it worked, thanks a lot! :)

**Comment by mattdmem** [comment]
Ok the cogs are turning v0.3.14 with this fix out soon!
