### ISSUE TITLE
Failed to generate pipeline report

### ISSUE THREAD

**Issue by jagos01** [epi2me-labs/wf-artic#5]
Hello,
I ran this workflow with the following command:
nextflow run epi2me-labs/wf-artic -c /media/MinION/MinIT_Data/Positive_std_artic/nf_config.cfg -w ${OUTPUT}/workspace -profile standard --fastq /media/MinION/MinIT_Data/APL_V1_V20/gfast_demux --samples /media/MinION/MinIT_Data/ARTIC_Analysis/APL_V1_V20/APL_V1_V20_sample_sheet.txt --out_dir ${OUTPUT}

All steps of the pipeline completed successfully except for pipeline:report which generated the following error: 

Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
  echo "--nextclade nextclade.json"
  report.py         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv --nextclade nextclade.json           --revision master --commit 5ecadc6704a123b2d15b0f4310b4674c2326dfda         --min_len 400 --max_len 700 --report_depth         100 --depths depth_stats/* --summaries read_stats/*         --bcftools_stats vcf_stats/*

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  Traceback (most recent call last):
    File "/home/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 330, in <module>
      main()
    File "/home/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 204, in main
      p = lines.line(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/lines.py", line 30, in line
      return simple(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/base.py", line 82, in simple
      p.y_range = Range1d(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/models/ranges.py", line 145, in __init__
      super().__init__(**kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/model.py", line 236, in __init__
      super().__init__(**kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/has_props.py", line 269, in __init__
      setattr(self, name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/has_props.py", line 298, in __setattr__
      super().__setattr__(name, value)
executor >  local (55)
[fa/36a705] process > checkSampleSheet (1)     [100%] 1 of 1 ✔
[a5/83c00b] process > pipeline:copySchemeDir   [100%] 1 of 1 ✔
[6b/913534] process > pipeline:preArticQC (19) [100%] 22 of 22 ✔
[8e/7ff09f] process > pipeline:runArtic (20)   [100%] 22 of 22 ✔
[fd/b4fb58] process > pipeline:allConsensus    [100%] 1 of 1 ✔
[e5/d9cb28] process > pipeline:allVariants     [100%] 1 of 1 ✔
[95/f3b5aa] process > pipeline:nextclade       [100%] 1 of 1 ✔
[d3/96b99a] process > pipeline:pangolin        [100%] 1 of 1 ✔
[b6/fcc7ef] process > pipeline:report          [100%] 1 of 1, failed: 1 ✘
[b3/7e1f6a] process > output (3)               [100%] 4 of 4 ✔
Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
  echo "--nextclade nextclade.json"
  report.py         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv --nextclade nextclade.json           --revision master --commit 5ecadc6704a123b2d15b0f4310b4674c2326dfda         --min_len 400 --max_len 700 --report_depth         100 --depths depth_stats/* --summaries read_stats/*         --bcftools_stats vcf_stats/*

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  Traceback (most recent call last):
    File "/home/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 330, in <module>
      main()
    File "/home/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 204, in main
      p = lines.line(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/lines.py", line 30, in line
      return simple(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/base.py", line 82, in simple
      p.y_range = Range1d(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/models/ranges.py", line 145, in __init__
      super().__init__(**kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/model.py", line 236, in __init__
      super().__init__(**kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/has_props.py", line 269, in __init__
      setattr(self, name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/has_props.py", line 298, in __setattr__
      super().__setattr__(name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 552, in __set__
      self._internal_set(obj, value, setter=setter)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 784, in _internal_set
      value = self.property.prepare_value(obj, self.name, value)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/bokeh/core/property/bases.py", line 350, in prepare_value
      raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
  ValueError: failed to validate Range1d(id='1237', ...).bounds: expected either None or a value of type MinMaxBounds(Auto, Tuple(Float, Float), Tuple(Nullable(Float), Float), Tuple(Float, Nullable(Float)), Tuple(TimeDelta, TimeDelta), Tuple(Nullable(TimeDelta), TimeDelta), Tuple(TimeDelta, Nullable(TimeDelta)), Tuple(Datetime, Datetime), Tuple(Nullable(Datetime), Datetime), Tuple(Datetime, Nullable(Datetime))), got (0.0, 0.0)

Do you have any suggestions the have the report generated?
Thanks,
Scott

**Comment by jagos01** [comment]
I ran the data through the pipeline again but without the negative control and the report file was generated.
