### ISSUE TITLE
[Bug]: Process 'pipeline:pangolin' terminated

### ISSUE THREAD

**Issue by leoncaly** [epi2me-labs/wf-artic#64]
### What happened?

A bug happened!

wf-artic pipeline fails at pipeline:pangolin.
This is occurring across multiple machines running Ubuntu 20 LTS.

The wf-artic pipeline was successfully run the morning (07:00) of 7th October, 2022 (Australian Eastern Standard Time).
When the same dataset was run at 17:00 the same day, the pipline:pangolin error occurred.

No changes to software or updates occurred during that time across all machines that A bug happened!

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Conda

### Workflow Version

v0.3.18

### Relevant log output

```shell
Error executing process > 'pipeline:pangolin'

Caused by:
  Process `pipeline:pangolin` terminated with an error exit status (1)

Command executed:

  if [ "true" == "true" ]
  then
    pangolin --update
  fi
  
  pangolin --all-versions 2>&1 | sed 's/: /,/' > pangolin.version
  pangolin  consensus.fasta

Command exit status:
  1

Command output:
  ****
  Pangolin running in usher mode.
  ****
  Maximum ambiguity allowed is 0.3.
  ****
  Query file:	consensus.fasta
  ****
  Data files found:
  usher_pb:	/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/pangolin_data/data/lineageTree.pb
  ****

Command error:
  pangolin updated to v4.1.2
  pangolin-data already latest release (v1.14)
  constellations already latest release (v0.1.10)
  scorpio already latest release (v0.3.17)
  Traceback (most recent call last):
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
      success = workflow.execute(
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/snakemake/workflow.py", line 1043, in execute
      logger.run_info("\n".join(dag.stats()))
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/snakemake/dag.py", line 2176, in stats
      yield tabulate(rows, headers="keys")
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
      list_of_lists, headers = _normalize_tabular_data(
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
      rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
      rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
      (len(row) >= 1 and row[0] == SEPARATING_LINE)
    File "/home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/conda/env-58325cec5ae12d717426507de369048a/lib/python3.8/site-packages/snakemake/rules.py", line 1127, in __eq__
      return self.name == other.name and self.output == other.output
  AttributeError: 'str' object has no attribute 'name'

Work dir:
  /home/leoncaly/Desktop/COVSEQ_Working/Analysis/221005078_analysis/work/1e/5ec8dba560dc6f2a622f59298ab0ee
```

**Comment by mattdmem** [comment]
Hello - thanks for your bug report.

This is an issue with tabulate which is used by snakemake, which is used by pangolin. I'll hopefully have a fix soon.

Thanks

Matt

**Comment by leoncaly** [comment]
Thank you Matt.  Is there a work around that I can implement at my end to get the pipeline up and running again?

**Comment by mattdmem** [comment]
This should be fixed now.
