### ISSUE TITLE
[Bug]: Error executing process > 'pipeline:report (1)'

### ISSUE THREAD

**Issue by myorick** [epi2me-labs/wf-artic#79]
### What happened?

Hello! Can someone please help?

I'm writing to ask for some help in generating the final reports. 
I have a library composed of 24 Native barcoded samples. the demultiplexed samples were submitted to nextflow wf-Artic v0.3.25-g77cdcbe. 

the code I was running is :
nextflow run epi2me-labs/wf-artic --fastq /Users/rick/covid_analysis/barcoded --scheme_version ARTIC/V4.1 --sample_sheet /Users/rick/covid_analysis/sample_sheet.csv --out_dir /Users/rick/covid_analysis/Nextflow_out --artic_threads 4 --pangolin_threads 4 --report_detailed --disable_ping

At the end when it generates the report, there is a error, saying:
  Traceback (most recent call last)
    File "/Users/rick/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow-glue", line 7, in <module>
      cli()
    File "/Users/rick/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/__init__.py", line 62, in cli
      args.func(args)
    File "/Users/rick/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/report.py", line 98, in main
      with open(args.telemetry) as f:
  TypeError: expected str, bytes or os.PathLike object, not NoneType:

### Operating System

macOS

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - EPI2ME Labs Versions

23.04.1

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

v0.3.25-g77cdcbe

### Relevant log output

```shell
nextflow run epi2me-labs/wf-artic  --fastq /Users/rick/covid_analysis/barcoded --scheme_version ARTIC/V4.1 --sample_sheet /Users/rick/covid_analysis/sample_sheet.csv --out_dir /Users/rick/covid_analysis/Nextflow_out --artic_threads 4 --pangolin_threads 4 --report_detailed --disable_ping
N E X T F L O W  ~  version 23.04.1
Launching `https://github.com/epi2me-labs/wf-artic` [silly_mclean] DSL2 - revision: 77cdcbee16 [master]

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-artic v0.3.25-g77cdcbe
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : silly_mclean
  containerEngine: docker
  launchDir      : /Users/rick
  workDir        : /Users/rick/work
  projectDir     : /Users/rick/.nextflow/assets/epi2me-labs/wf-artic
  userName       : rick
  profile        : standard
  configFiles    : /Users/rick/.nextflow/assets/epi2me-labs/wf-artic/nextflow.config

Input Options
  fastq          : /Users/rick/covid_analysis/barcoded

Primer Scheme Selection
  scheme_version : ARTIC/V4.1

Sample Options
  sample_sheet   : /Users/rick/covid_analysis/sample_sheet.csv

Output Options
  out_dir        : /Users/rick/covid_analysis/Nextflow_out

Reporting Options
  report_detailed: true

Miscellaneous Options
  disable_ping   : true

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-artic for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-artic v0.3.25-g77cdcbe.
--------------------------------------------------------------------------------

      ------------------------------------
      Available Primer Schemes:
      ------------------------------------
      
  Name		Version
  SARS-CoV-2	ARTIC/V1	
  SARS-CoV-2	ARTIC/V2	
  SARS-CoV-2	ARTIC/V4	
  SARS-CoV-2	ARTIC/V3	
  SARS-CoV-2	ARTIC/V4.1	
  SARS-CoV-2	Midnight-IDT/V1	
  SARS-CoV-2	NEB-VarSkip/v2b	
  SARS-CoV-2	NEB-VarSkip/v1a-long	
  SARS-CoV-2	NEB-VarSkip/v2	
  SARS-CoV-2	NEB-VarSkip/v1a	
  SARS-CoV-2	Midnight-ONT/V1	
  SARS-CoV-2	Midnight-ONT/V2	
  SARS-CoV-2	Midnight-ONT/V3	

      ------------------------------------
      
Checking fastq input.
executor >  local (129)
[9b/7b3003] process > validate_sample_sheet   [100%] 1 of 1, cached: 1 ✔
[ab/0a96f6] process > fastcat (24)            [100%] 24 of 24, cached: 24 ✔
[c6/f4149d] process > pipeline:getVersions    [100%] 1 of 1, cached: 1 ✔
[93/166640] process > pipeline:getParams      [100%] 1 of 1, cached: 1 ✔
[c1/01dc08] process > pipeline:runArtic (24)  [100%] 24 of 24, cached: 2 ✔
[c9/75aff2] process > pipeline:combineDepth   [100%] 1 of 1 ✔
[5f/6ca6e8] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[00/9046b2] process > pipeline:allVariants    [100%] 1 of 1 ✔
[ed/beef61] process > pipeline:prep_nextclade [100%] 1 of 1, cached: 1 ✔
[c1/d9f9e9] process > pipeline:nextclade      [100%] 1 of 1 ✔
[70/62c017] process > pipeline:pangolin       [100%] 1 of 1 ✔
[c2/4fa49a] process > pipeline:report (1)     [  0%] 0 of 1
[e6/428062] process > output (100)            [100%] 101 of 101
ERROR ~ Error executing process > 'pipeline:report (1)'

Caused by:
  Process `pipeline:report (1)` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo '[
      {
          "barcode": "barcode02",
          "type": "test_sample",
          "alias": "sample_2"
      },
      {
          "barcode": "barcode11",
          "type": "test_sample",
          "alias": "sample_11"
      },
      {
          "barcode": "barcode03",
          "type": "test_sample",
          "alias": "sample_3"
      },
      {
          "barcode": "barcode09",
          "type": "test_sample",
          "alias": "sample_9"
      },
      {
          "barcode": "barcode10",
          "type": "test_sample",
          "alias": "sample_10"
      },
      {
          "barcode": "barcode12",
          "type": "test_sample",
          "alias": "sample_12"
      },
      {
          "barcode": "barcode05",
          "type": "test_sample",
          "alias": "sample_5"
      },
      {
          "barcode": "barcode06",
          "type": "test_sample",
          "alias": "sample_6"
      },
      {
          "barcode": "barcode04",
          "type": "test_sample",
          "alias": "sample_4"
      },
      {
          "barcode": "barcode01",
          "type": "test_sample",
          "alias": "sample_1"
      },
      {
          "barcode": "barcode08",
          "type": "test_sample",
          "alias": "sample_8"
      },
      {
          "barcode": "barcode07",
          "type": "test_sample",
          "alias": "sample_7"
      },
      {
          "barcode": "barcode16",
          "type": "test_sample",
          "alias": "sample_16"
      },
      {
          "barcode": "barcode14",
          "type": "test_sample",
          "alias": "sample_14"
      },
      {
          "barcode": "barcode21",
          "type": "test_sample",
          "alias": "sample_21"
      },
      {
          "barcode": "barcode17",
          "type": "test_sample",
          "alias": "sample_17"
      },
      {
          "barcode": "barcode22",
          "type": "test_sample",
          "alias": "sample_22"
      },
      {
          "barcode": "barcode18",
          "type": "test_sample",
          "alias": "sample_18"
      },
      {
          "barcode": "barcode15",
          "type": "test_sample",
          "alias": "sample_15"
      },
      {
          "barcode": "barcode20",
          "type": "test_sample",
          "alias": "sample_20"
      },
      {
          "barcode": "barcode13",
          "type": "test_sample",
          "alias": "sample_13"
      },
      {
          "barcode": "barcode23",
          "type": "test_sample",
          "alias": "sample_23"
      },
      {
          "barcode": "barcode19",
          "type": "test_sample",
          "alias": "sample_19"
      },
      {
          "barcode": "barcode24",
          "type": "test_sample",
          "alias": "sample_24"
      }
  ]' > metadata.json
      workflow-glue report         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv           --nextclade nextclade.json          --nextclade_errors consensus.errors.csv         --revision master         --commit 77cdcbee16db483deb7cfdfc4c88d05f821c430c         --min_len 400         --max_len 700         --report_depth 100         --depths depth_stats/*         --fastcat_stats per-read-stats.tsv         --bcftools_stats vcf_stats/*          --versions versions         --params params.json         --consensus_fasta consensus_fasta         --metadata metadata.json

Command exit status:
executor >  local (129)
[9b/7b3003] process > validate_sample_sheet   [100%] 1 of 1, cached: 1 ✔
[ab/0a96f6] process > fastcat (24)            [100%] 24 of 24, cached: 24 ✔
[c6/f4149d] process > pipeline:getVersions    [100%] 1 of 1, cached: 1 ✔
[93/166640] process > pipeline:getParams      [100%] 1 of 1, cached: 1 ✔
[c1/01dc08] process > pipeline:runArtic (24)  [100%] 24 of 24, cached: 2 ✔
[c9/75aff2] process > pipeline:combineDepth   [100%] 1 of 1 ✔
[5f/6ca6e8] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[00/9046b2] process > pipeline:allVariants    [100%] 1 of 1 ✔
[ed/beef61] process > pipeline:prep_nextclade [100%] 1 of 1, cached: 1 ✔
[c1/d9f9e9] process > pipeline:nextclade      [100%] 1 of 1 ✔
[70/62c017] process > pipeline:pangolin       [100%] 1 of 1 ✔
[c2/4fa49a] process > pipeline:report (1)     [100%] 1 of 1, failed: 1 ✘
[e6/428062] process > output (100)            [ 98%] 101 of 103
ERROR ~ Error executing process > 'pipeline:report (1)'

Caused by:
  Process `pipeline:report (1)` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo '[
      {
          "barcode": "barcode02",
          "type": "test_sample",
          "alias": "sample_2"
      },
      {
          "barcode": "barcode11",
          "type": "test_sample",
          "alias": "sample_11"
      },
      {
          "barcode": "barcode03",
          "type": "test_sample",
          "alias": "sample_3"
      },
      {
          "barcode": "barcode09",
          "type": "test_sample",
          "alias": "sample_9"
      },
      {
          "barcode": "barcode10",
          "type": "test_sample",
          "alias": "sample_10"
      },
      {
          "barcode": "barcode12",
          "type": "test_sample",
          "alias": "sample_12"
      },
      {
          "barcode": "barcode05",
          "type": "test_sample",
          "alias": "sample_5"
      },
      {
          "barcode": "barcode06",
          "type": "test_sample",
          "alias": "sample_6"
      },
      {
          "barcode": "barcode04",
          "type": "test_sample",
          "alias": "sample_4"
      },
      {
          "barcode": "barcode01",
          "type": "test_sample",
          "alias": "sample_1"
      },
      {
          "barcode": "barcode08",
          "type": "test_sample",
          "alias": "sample_8"
      },
      {
          "barcode": "barcode07",
          "type": "test_sample",
          "alias": "sample_7"
      },
      {
          "barcode": "barcode16",
          "type": "test_sample",
          "alias": "sample_16"
      },
      {
          "barcode": "barcode14",
          "type": "test_sample",
          "alias": "sample_14"
      },
      {
          "barcode": "barcode21",
          "type": "test_sample",
          "alias": "sample_21"
      },
      {
          "barcode": "barcode17",
          "type": "test_sample",
          "alias": "sample_17"
      },
      {
          "barcode": "barcode22",
          "type": "test_sample",
          "alias": "sample_22"
      },
      {
          "barcode": "barcode18",
          "type": "test_sample",
          "alias": "sample_18"
      },
      {
          "barcode": "barcode15",
          "type": "test_sample",
          "alias": "sample_15"
      },
      {
          "barcode": "barcode20",
          "type": "test_sample",
          "alias": "sample_20"
      },
      {
          "barcode": "barcode13",
          "type": "test_sample",
          "alias": "sample_13"
      },
      {
          "barcode": "barcode23",
          "type": "test_sample",
          "alias": "sample_23"
      },
      {
          "barcode": "barcode19",
          "type": "test_sample",
          "alias": "sample_19"
      },
      {
          "barcode": "barcode24",
          "type": "test_sample",
          "alias": "sample_24"
      }
  ]' > metadata.json
      workflow-glue report         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv           --nextclade nextclade.json          --nextclade_errors consensus.errors.csv         --revision master         --commit 77cdcbee16db483deb7cfdfc4c88d05f821c430c         --min_len 400         --max_len 700         --report_depth 100         --depths depth_stats/*         --fastcat_stats per-read-stats.tsv         --bcftools_stats vcf_stats/*          --versions versions         --params params.json         --consensus_fasta consensus_fasta         --metadata metadata.json

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  --pangolin pangolin.csv
  --nextclade nextclade.json
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  [10:51:15 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/Users/rick/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow-glue", line 7, in <module>
      cli()
    File "/Users/rick/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/__init__.py", line 62, in cli
      args.func(args)
    File "/Users/rick/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/report.py", line 98, in main
      with open(args.telemetry) as f:
  TypeError: expected str, bytes or os.PathLike object, not NoneType

Work dir:
  /Users/rick/work/c2/4fa49a0fd532a912bd8c8982bbd532

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

**Comment by vlshesketh** [comment]
Hello, thank you for reporting this issue. It is caused by using the '--report_detailed' parameter. We will release an update version of the workflow shortly which removes this parameter as an option, but in the meantime you should be able to generate a report by omitting this option from your Nextflow command.
