### ISSUE TITLE
Sample sheet with integer sample names error

### ISSUE THREAD

**Issue by geocarvalho** [epi2me-labs/wf-artic#8]
Hello @cjw85, thanks to make the project available.
Every time we have a sample name with just numbers inside our sample sheet for the `--sample` parameter with other sample names as a string the pipeline crashes in the `report` step.

* Samplesheet
```
barcode,sample_name
barcode01,sample01
barcode02,20210818
barcode03,sample03
barcode04,sample04
barcode05,sample05
```

* Command example and error
```
/path/to/nextflow run /path/to/wf-artic/main.nf --fastq /path/to/fastq_pass --out_dir /path/to/output -w /path/to/work/ --samples /path/to/samplesheet.csv -resume
N E X T F L O W  ~  version 20.10.0
Launching `/path/to/wf-artic/main.nf` [desperate_archimedes] - revision: f6f86e18c7
WARN: Access to undefined parameter `detect_samples` -- Initialise it to a default value eg. `params.detect_samples = some_value`

Parameter summary
=================
    help: false
    out_dir: /path/to/output
    fastq: /path/to/fastq_pass
    sanitize_fastq: false
    samples: /path/to/samplesheet.csv
    report_depth: 100
    medaka_model: r941_prom_variant_g360
    scheme_name: SARS-CoV-2
    scheme_version: V3
    genotype_variants: null
    report_clade: true
    report_lineage: true
    report_coverage: true
    report_variant_summary: true
    wfversion: v0.3.2
    aws_image_prefix: null
    aws_queue: null
    lab_id: null
    testkit: null
    _min_len: 400
    _max_len: 700

Checking sample sheet.
Checking input directory structure.
[-        ] process > checkSampleSheet -
executor >  local (30)
[c9/d4bd0d] process > checkSampleSheet (1)    [100%] 1 of 1 ✔
[98/bc48a2] process > pipeline:get_versions   [100%] 1 of 1, cached: 1 ✔
[f2/faa4fb] process > pipeline:copySchemeDir  [100%] 1 of 1, cached: 1 ✔
[f1/d3bd35] process > pipeline:preArticQC (4) [100%] 5 of 5 ✔
[48/c30c77] process > pipeline:runArtic (4)   [100%] 5 of 5 ✔
[2a/7b1c6a] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[9d/d3aee4] process > pipeline:allVariants    [100%] 1 of 1 ✔
[07/9574bd] process > pipeline:nextclade      [100%] 1 of 1 ✔
[d4/2a244a] process > pipeline:pangolin       [100%] 1 of 1 ✔
[ee/090cbc] process > pipeline:report         [  0%] 0 of 1
[b6/01e9b2] process > output (4)              [100%] 14 of 14
/path/to/work/2a/7b1c6a28ac090e0560f0f3398a725c/all_consensus.fasta
/path/to/work/2a/7b1c6a28ac090e0560f0f3398a725c/consensus_status.txt
/path/to/work/9d/d3aee4ebfca7cec6fe7d45ded62ef2/all_variants.vcf.gz
/path/to/work/9d/d3aee4ebfca7cec6fe7d45ded62ef2/all_variants.vcf.gz.tbi
/path/to/work/b4/7019d23562194a22d51d6e03d93581/sample03.primertrimmed.rg.sorted.bam
/path/to/work/b4/7019d23562194a22d51d6e03d93581/sample03.primertrimmed.rg.sorted.bam.bai
/path/to/work/df/14968a22ca46e3a526a456769b0352/sample05.primertrimmed.rg.sorted.bam
/path/to/work/df/14968a22ca46e3a526a456769b0352/sample05.primertrimmed.rg.sorted.bam.bai
/path/to/work/17/fbabd0fa52c6649c1307d1b4356343/sample01.primertrimmed.rg.sorted.bam
/path/to/work/17/fbabd0fa52c6649c1307d1b4356343/sample01.primertrimmed.rg.sorted.bam.bai
/path/to/work/80/30b97c5b5ec73f7c9fdf715c076e6c/20210818.primertrimmed.rg.sorted.bam
/path/to/work/80/30b97c5b5ec73f7c9fdf715c076e6c/20210818.primertrimmed.rg.sorted.bam.bai
/path/to/work/48/c30c77e0b749d84d27086b2b8423e0/sample04.primertrimmed.rg.sorted.bam
/path/to/work/48/c30c77e0b749d84d27086b2b8423e0/sample04.primertrimmed.rg.sorted.bam.bai

Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo "help,false
  out_dir,/path/to/output
  fastq,/path/to/fastq_pass
  sanitize_fastq,false
  samples,/path/to/samplesheet.csv
  report_depth,100
  medaka_model,r941_prom_variant_g360
  scheme_name,SARS-CoV-2
  scheme_version,V3
  genotype_variants,null
  report_clade,true
  report_lineage,true
  report_coverage,true
  report_variant_summary,true
  wfversion,v0.3.2
  aws_image_prefix,null

executor >  local (30)
[c9/d4bd0d] process > checkSampleSheet (1)    [100%] 1 of 1 ✔
[98/bc48a2] process > pipeline:get_versions   [100%] 1 of 1, cached: 1 ✔
[f2/faa4fb] process > pipeline:copySchemeDir  [100%] 1 of 1, cached: 1 ✔
[f1/d3bd35] process > pipeline:preArticQC (4) [100%] 5 of 5 ✔
[48/c30c77] process > pipeline:runArtic (4)   [100%] 5 of 5 ✔
[2a/7b1c6a] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[9d/d3aee4] process > pipeline:allVariants    [100%] 1 of 1 ✔
[07/9574bd] process > pipeline:nextclade      [100%] 1 of 1 ✔
[d4/2a244a] process > pipeline:pangolin       [100%] 1 of 1 ✔
[ee/090cbc] process > pipeline:report         [100%] 1 of 1, failed: 1 ✘
[b6/01e9b2] process > output (4)              [100%] 14 of 14 ✔
/path/to/work/2a/7b1c6a28ac090e0560f0f3398a725c/all_consensus.fasta
/path/to/work/2a/7b1c6a28ac090e0560f0f3398a725c/consensus_status.txt
/path/to/work/9d/d3aee4ebfca7cec6fe7d45ded62ef2/all_variants.vcf.gz
/path/to/work/9d/d3aee4ebfca7cec6fe7d45ded62ef2/all_variants.vcf.gz.tbi
/path/to/work/b4/7019d23562194a22d51d6e03d93581/sample03.primertrimmed.rg.sorted.bam
/path/to/work/b4/7019d23562194a22d51d6e03d93581/sample03.primertrimmed.rg.sorted.bam.bai
/path/to/work/df/14968a22ca46e3a526a456769b0352/sample05.primertrimmed.rg.sorted.bam
/path/to/work/df/14968a22ca46e3a526a456769b0352/sample05.primertrimmed.rg.sorted.bam.bai
/path/to/work/17/fbabd0fa52c6649c1307d1b4356343/sample01.primertrimmed.rg.sorted.bam
/path/to/work/17/fbabd0fa52c6649c1307d1b4356343/sample01.primertrimmed.rg.sorted.bam.bai
/path/to/work/80/30b97c5b5ec73f7c9fdf715c076e6c/20210818.primertrimmed.rg.sorted.bam
/path/to/work/80/30b97c5b5ec73f7c9fdf715c076e6c/20210818.primertrimmed.rg.sorted.bam.bai
/path/to/work/48/c30c77e0b749d84d27086b2b8423e0/sample04.primertrimmed.rg.sorted.bam
/path/to/work/48/c30c77e0b749d84d27086b2b8423e0/sample04.primertrimmed.rg.sorted.bam.bai


Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo "help,false
  out_dir,/path/to/output
  fastq,/path/to/fastq_pass
  sanitize_fastq,false
  samples,/path/to/samplesheet.csv
  report_depth,100
  medaka_model,r941_prom_variant_g360
  scheme_name,SARS-CoV-2
  scheme_version,V3
  genotype_variants,null
  report_clade,true
  report_lineage,true
  report_coverage,true
  report_variant_summary,true
  wfversion,v0.3.2
  aws_image_prefix,null
  aws_queue,null
  lab_id,null
  testkit,null
  _min_len,400
  _max_len,700
  full_scheme_name,SARS-CoV-2/V3" > params.csv
      report.py         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv --nextclade nextclade.json           --revision null --params params.csv --commit null         --min_len 400 --max_len 700 --report_depth         100 --depths depth_stats/* --summaries read_stats/*         --bcftools_stats vcf_stats/*          --versions versions

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  Traceback (most recent call last):
    File "/bix_resources/tools/wf-artic/bin/report.py", line 371, in <module>
      main()
    File "/bix_resources/tools/wf-artic/bin/report.py", line 163, in main
      pd.DataFrame(good_reads['sample_name'].value_counts())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 5582, in sort_index
      return super().sort_index(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 4537, in sort_index
      indexer = get_indexer_indexer(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/sorting.py", line 87, in get_indexer_indexer
      indexer = nargsort(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/sorting.py", line 368, in nargsort
      return items.argsort(ascending=ascending, kind=kind, na_position=na_position)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/arrays/base.py", line 586, in argsort
      return nargsort(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/sorting.py", line 380, in nargsort
      indexer = non_nan_idx[non_nans.argsort(kind=kind)]
  TypeError: '<' not supported between instances of 'int' and 'str'

Work dir:
  /path/to/work/ee/090cbcb4dd8b06d739e9fb6b0bd399

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
```

Could you help us with that?

**Comment by cjw85** [comment]
Hi @geocarvalho,

Thank you for reporting this, we'll take a look.

**Comment by ammaraziz** [comment]
I am getting this error on the latest wf-artic version. Any idea what's causing it? My sample names (`alias`) are ints.

Any idea what causing this issue?
