### ISSUE TITLE
ERROR ~ Error executing process > 'pipeline:report (1)'

### ISSUE THREAD

**Issue by Habibk91** [epi2me-labs/wf-artic#88]
### Operating System

Ubuntu 22.04

### Workflow Version

v0.3.29-g98641c5

### Workflow Execution

Command line

### EPI2ME Version

v5.1.1

### CLI command run

nextflow run epi2me-labs/wf-artic -c myconfig.cfg --fastq "Ngs-trial-3/barcoded_samples2/" --sample_sheet sample_sheet3.csv --out_dir "trial-3_results/"

### Workflow Execution - CLI Execution Profile

custom

### What happened?

i am getting the below error:
ERROR ~ Error executing process > 'pipeline:report (1)'

Caused by:
  Process `pipeline:report (1)` terminated with an error exit status (1)

### Relevant log output

```shell
Checking fastq input.
executor >  local (292)
[76/b81040] process > validate_sample_sheet                    [100%] 1 of 1 ✔
[9b/363df1] process > fastcat (46)                             [100%] 46 of 46 ✔
[03/66068b] process > pipeline:getVersions                     [100%] 1 of 1 ✔
[d2/44200e] process > pipeline:getParams                       [100%] 1 of 1 ✔
[f3/7f68a6] process > pipeline:lookup_medaka_variant_model (1) [100%] 1 of 1 ✔
[2d/6384f7] process > pipeline:runArtic (46)                   [100%] 46 of 46 ✔
[98/e94c3b] process > pipeline:combineDepth                    [100%] 1 of 1 ✔
[21/c3260a] process > pipeline:allConsensus                    [100%] 1 of 1 ✔
[b3/6b1aea] process > pipeline:allVariants                     [100%] 1 of 1 ✔
[68/cc4d89] process > pipeline:prep_nextclade                  [100%] 1 of 1 ✔
[cc/cec4d9] process > pipeline:nextclade                       [100%] 1 of 1 ✔
[b9/d89e84] process > pipeline:pangolin                        [100%] 1 of 1 ✔
[97/8759d7] process > pipeline:report (1)                      [  0%] 0 of 1
[96/c53d40] process > output (189)                             [100%] 189 of 189
ERROR ~ Error executing process > 'pipeline:report (1)'

Caused by:
  Process `pipeline:report (1)` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo '[
      {
          "barcode": "barcode27",
          "type": "test_sample",
          "sample_id": "AB_103",
          "alias": "AB_103"
      },
      {
          "barcode": "barcode37",
          "type": "test_sample",
          "sample_id": "AB_115",
          "alias": "AB_115"
      },
      {
          "barcode": "barcode34",
          "type": "test_sample",
          "sample_id": "AB_110",
          "alias": "AB_110"
      },
      {
          "barcode": "barcode35",
          "type": "test_sample",
          "sample_id": "AB_113",
          "alias": "AB_113"
      },
      {
          "barcode": "barcode29",
          "type": "test_sample",
          "sample_id": "AB_105",
          "alias": "AB_105"
      },
      {
          "barcode": "barcode31",
          "type": "test_sample",
          "sample_id": "AB_107",
          "alias": "AB_107"
      },
      {
          "barcode": "barcode25",
          "type": "test_sample",
          "sample_id": "AB_101",
          "alias": "AB_101"
      },
      {
          "barcode": "barcode30",
          "type": "test_sample",
          "sample_id": "AB_106",
          "alias": "AB_106"
      },
      {
          "barcode": "barcode47",
          "type": "test_sample",
          "sample_id": "AB_125",
          "alias": "AB_125"
      },
      {
          "barcode": "barcode28",
          "type": "test_sample",
          "sample_id": "AB_104",
          "alias": "AB_104"
      },
      {
          "barcode": "barcode38",
          "type": "test_sample",
          "sample_id": "AB_116",
          "alias": "AB_116"
      },
      {
          "barcode": "barcode33",
          "type": "test_sample",
          "sample_id": "AB_109",
          "alias": "AB_109"
      },
      {
          "barcode": "barcode41",
          "type": "test_sample",
          "sample_id": "AB_119",
          "alias": "AB_119"
      },
      {
          "barcode": "barcode46",
          "type": "test_sample",
          "sample_id": "AB_124",
          "alias": "AB_124"
      },
      {
          "barcode": "barcode26",
          "type": "test_sample",
          "sample_id": "AB_102",
          "alias": "AB_102"
      },
      {
          "barcode": "barcode32",
          "type": "test_sample",
          "sample_id": "AB_108",
          "alias": "AB_108"
      },
      {
          "barcode": "barcode39",
          "type": "test_sample",
          "sample_id": "AB_117",
          "alias": "AB_117"
      },
      {
          "barcode": "barcode45",
          "type": "test_sample",
          "sample_id": "AB_123",
          "alias": "AB_123"
      },
      {
          "barcode": "barcode53",
          "type": "test_sample",
          "sample_id": "AB_131",
          "alias": "AB_131"
      },
      {
          "barcode": "barcode54",
          "type": "test_sample",
          "sample_id": "SG_101",
          "alias": "SG_101"
      },
      {
          "barcode": "barcode52",
          "type": "test_sample",
          "sample_id": "AB_130",
          "alias": "AB_130"
      },
      {
          "barcode": "barcode58",
          "type": "test_sample",
          "sample_id": "SG_105",
          "alias": "SG_105"
      },
      {
          "barcode": "barcode40",
          "type": "test_sample",
          "sample_id": "AB_118",
          "alias": "AB_118"
      },
      {
          "barcode": "barcode51",
          "type": "test_sample",
          "sample_id": "AB_129",
          "alias": "AB_129"
      },
      {
          "barcode": "barcode49",
          "type": "test_sample",
          "sample_id": "AB_127",
          "alias": "AB_127"
      },
      {
          "barcode": "barcode50",
          "type": "test_sample",
          "sample_id": "AB_128",
          "alias": "AB_128"
      },
      {
          "barcode": "barcode48",
          "type": "test_sample",
          "sample_id": "AB_126",
          "alias": "AB_126"
      },
      {
          "barcode": "barcode57",
          "type": "test_sample",
          "sample_id": "SG_104",
          "alias": "SG_104"
      },
      {
          "barcode": "barcode43",
          "type": "test_sample",
          "sample_id": "AB_121",
          "alias": "AB_121"
      },
      {
          "barcode": "barcode55",
          "type": "test_sample",
          "sample_id": "SG_102",
          "alias": "SG_102"
      },
      {
          "barcode": "barcode42",
          "type": "test_sample",
          "sample_id": "AB_120",
          "alias": "AB_120"
      },
      {
          "barcode": "barcode65",
          "type": "test_sample",
          "sample_id": "SG_112",
          "alias": "SG_112"
      },
      {
          "barcode": "barcode59",
          "type": "test_sample",
          "sample_id": "SG_106",
          "alias": "SG_106"
      },
      {
          "barcode": "barcode56",
          "type": "test_sample",
          "sample_id": "SG_103",
          "alias": "SG_103"
      },
      {
          "barcode": "barcode60",
          "type": "test_sample",
          "sample_id": "SG_107",
          "alias": "SG_107"
      },
      {
          "barcode": "barcode62",
          "type": "test_sample",
          "sample_id": "SG_109",
          "alias": "SG_109"
      },
      {
          "barcode": "barcode61",
          "type": "test_sample",
          "sample_id": "SG_108",
          "alias": "SG_108"
      },
      {
          "barcode": "barcode69",
          "type": "test_sample",
          "sample_id": "SG_116",
          "alias": "SG_116"
      },
      {
          "barcode": "barcode70",
          "type": "test_sample",
          "sample_id": "SG_117",
          "alias": "SG_117"
      },
      {
          "barcode": "barcode64",
          "type": "test_sample",
          "sample_id": "SG_111",
          "alias": "SG_111"
      },
      {
          "barcode": "barcode63",
          "type": "test_sample",
          "sample_id": "SG_110",
          "alias": "SG_110"
      },
      {
          "barcode": "barcode66",
          "type": "test_sample",
          "sample_id": "SG_113",
          "alias": "SG_113"
      },
      {
          "barcode": "barcode68",
          "type": "test_sample",
          "sample_id": "SG_115",
          "alias": "SG_115"
      },
      {
          "barcode": "barcode71",
          "type": "test_sample",
          "sample_id": "Negative",
          "alias": "Negative"
      },
      {
          "barcode": "barcode67",
          "type": "test_sample",
          "sample_id": "SG_114",
executor >  local (292)
[76/b81040] process > validate_sample_sheet                    [100%] 1 of 1 ✔
[9b/363df1] process > fastcat (46)                             [100%] 46 of 46 ✔
[03/66068b] process > pipeline:getVersions                     [100%] 1 of 1 ✔
[d2/44200e] process > pipeline:getParams                       [100%] 1 of 1 ✔
[f3/7f68a6] process > pipeline:lookup_medaka_variant_model (1) [100%] 1 of 1 ✔
[2d/6384f7] process > pipeline:runArtic (46)                   [100%] 46 of 46 ✔
[98/e94c3b] process > pipeline:combineDepth                    [100%] 1 of 1 ✔
[21/c3260a] process > pipeline:allConsensus                    [100%] 1 of 1 ✔
[b3/6b1aea] process > pipeline:allVariants                     [100%] 1 of 1 ✔
[68/cc4d89] process > pipeline:prep_nextclade                  [100%] 1 of 1 ✔
[cc/cec4d9] process > pipeline:nextclade                       [100%] 1 of 1 ✔
[b9/d89e84] process > pipeline:pangolin                        [100%] 1 of 1 ✔
[97/8759d7] process > pipeline:report (1)                      [100%] 1 of 1, failed: 1 ✘
[96/c53d40] process > output (189)                             [ 98%] 189 of 191
ERROR ~ Error executing process > 'pipeline:report (1)'

Caused by:
  Process `pipeline:report (1)` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo '[
      {
          "barcode": "barcode27",
          "type": "test_sample",
          "sample_id": "AB_103",
          "alias": "AB_103"
      },
      {
          "barcode": "barcode37",
          "type": "test_sample",
          "sample_id": "AB_115",
          "alias": "AB_115"
      },
      {
          "barcode": "barcode34",
          "type": "test_sample",
          "sample_id": "AB_110",
          "alias": "AB_110"
      },
      {
          "barcode": "barcode35",
          "type": "test_sample",
          "sample_id": "AB_113",
          "alias": "AB_113"
      },
      {
          "barcode": "barcode29",
          "type": "test_sample",
          "sample_id": "AB_105",
          "alias": "AB_105"
      },
      {
          "barcode": "barcode31",
          "type": "test_sample",
          "sample_id": "AB_107",
          "alias": "AB_107"
      },
      {
          "barcode": "barcode25",
          "type": "test_sample",
          "sample_id": "AB_101",
          "alias": "AB_101"
      },
      {
          "barcode": "barcode30",
          "type": "test_sample",
          "sample_id": "AB_106",
          "alias": "AB_106"
      },
      {
          "barcode": "barcode47",
          "type": "test_sample",
          "sample_id": "AB_125",
          "alias": "AB_125"
      },
      {
          "barcode": "barcode28",
          "type": "test_sample",
          "sample_id": "AB_104",
          "alias": "AB_104"
      },
      {
          "barcode": "barcode38",
          "type": "test_sample",
          "sample_id": "AB_116",
          "alias": "AB_116"
      },
      {
          "barcode": "barcode33",
          "type": "test_sample",
          "sample_id": "AB_109",
          "alias": "AB_109"
      },
      {
          "barcode": "barcode41",
          "type": "test_sample",
          "sample_id": "AB_119",
          "alias": "AB_119"
      },
      {
          "barcode": "barcode46",
          "type": "test_sample",
          "sample_id": "AB_124",
          "alias": "AB_124"
      },
      {
          "barcode": "barcode26",
          "type": "test_sample",
          "sample_id": "AB_102",
          "alias": "AB_102"
      },
      {
          "barcode": "barcode32",
          "type": "test_sample",
          "sample_id": "AB_108",
          "alias": "AB_108"
      },
      {
          "barcode": "barcode39",
          "type": "test_sample",
          "sample_id": "AB_117",
          "alias": "AB_117"
      },
      {
          "barcode": "barcode45",
          "type": "test_sample",
          "sample_id": "AB_123",
          "alias": "AB_123"
      },
      {
          "barcode": "barcode53",
          "type": "test_sample",
          "sample_id": "AB_131",
          "alias": "AB_131"
      },
      {
          "barcode": "barcode54",
          "type": "test_sample",
          "sample_id": "SG_101",
          "alias": "SG_101"
      },
      {
          "barcode": "barcode52",
          "type": "test_sample",
          "sample_id": "AB_130",
          "alias": "AB_130"
      },
      {
          "barcode": "barcode58",
          "type": "test_sample",
          "sample_id": "SG_105",
          "alias": "SG_105"
      },
      {
          "barcode": "barcode40",
          "type": "test_sample",
          "sample_id": "AB_118",
          "alias": "AB_118"
      },
      {
          "barcode": "barcode51",
          "type": "test_sample",
          "sample_id": "AB_129",
          "alias": "AB_129"
      },
      {
          "barcode": "barcode49",
          "type": "test_sample",
          "sample_id": "AB_127",
          "alias": "AB_127"
      },
      {
          "barcode": "barcode50",
          "type": "test_sample",
          "sample_id": "AB_128",
          "alias": "AB_128"
      },
      {
          "barcode": "barcode48",
          "type": "test_sample",
          "sample_id": "AB_126",
          "alias": "AB_126"
      },
      {
          "barcode": "barcode57",
          "type": "test_sample",
          "sample_id": "SG_104",
          "alias": "SG_104"
      },
      {
          "barcode": "barcode43",
          "type": "test_sample",
          "sample_id": "AB_121",
          "alias": "AB_121"
      },
      {
          "barcode": "barcode55",
          "type": "test_sample",
          "sample_id": "SG_102",
          "alias": "SG_102"
      },
      {
          "barcode": "barcode42",
          "type": "test_sample",
          "sample_id": "AB_120",
          "alias": "AB_120"
      },
      {
          "barcode": "barcode65",
          "type": "test_sample",
          "sample_id": "SG_112",
          "alias": "SG_112"
      },
      {
          "barcode": "barcode59",
          "type": "test_sample",
          "sample_id": "SG_106",
          "alias": "SG_106"
      },
      {
          "barcode": "barcode56",
          "type": "test_sample",
          "sample_id": "SG_103",
          "alias": "SG_103"
      },
      {
          "barcode": "barcode60",
          "type": "test_sample",
          "sample_id": "SG_107",
          "alias": "SG_107"
      },
      {
          "barcode": "barcode62",
          "type": "test_sample",
          "sample_id": "SG_109",
          "alias": "SG_109"
      },
      {
          "barcode": "barcode61",
          "type": "test_sample",
          "sample_id": "SG_108",
          "alias": "SG_108"
      },
      {
          "barcode": "barcode69",
          "type": "test_sample",
          "sample_id": "SG_116",
          "alias": "SG_116"
      },
      {
          "barcode": "barcode70",
          "type": "test_sample",
          "sample_id": "SG_117",
          "alias": "SG_117"
      },
      {
          "barcode": "barcode64",
          "type": "test_sample",
          "sample_id": "SG_111",
          "alias": "SG_111"
      },
      {
          "barcode": "barcode63",
          "type": "test_sample",
          "sample_id": "SG_110",
          "alias": "SG_110"
      },
      {
          "barcode": "barcode66",
          "type": "test_sample",
          "sample_id": "SG_113",
          "alias": "SG_113"
      },
      {
          "barcode": "barcode68",
          "type": "test_sample",
          "sample_id": "SG_115",
          "alias": "SG_115"
      },
      {
          "barcode": "barcode71",
          "type": "test_sample",
          "sample_id": "Negative",
          "alias": "Negative"
      },
      {
          "barcode": "barcode67",
          "type": "test_sample",
          "sample_id": "SG_114",
executor >  local (292)
[76/b81040] process > validate_sample_sheet                    [100%] 1 of 1 ✔
[9b/363df1] process > fastcat (46)                             [100%] 46 of 46 ✔
[03/66068b] process > pipeline:getVersions                     [100%] 1 of 1 ✔
[d2/44200e] process > pipeline:getParams                       [100%] 1 of 1 ✔
[f3/7f68a6] process > pipeline:lookup_medaka_variant_model (1) [100%] 1 of 1 ✔
[2d/6384f7] process > pipeline:runArtic (46)                   [100%] 46 of 46 ✔
[98/e94c3b] process > pipeline:combineDepth                    [100%] 1 of 1 ✔
[21/c3260a] process > pipeline:allConsensus                    [100%] 1 of 1 ✔
[b3/6b1aea] process > pipeline:allVariants                     [100%] 1 of 1 ✔
[68/cc4d89] process > pipeline:prep_nextclade                  [100%] 1 of 1 ✔
[cc/cec4d9] process > pipeline:nextclade                       [100%] 1 of 1 ✔
[b9/d89e84] process > pipeline:pangolin                        [100%] 1 of 1 ✔
[97/8759d7] process > pipeline:report (1)                      [100%] 1 of 1, failed: 1 ✘
[96/c53d40] process > output (189)                             [ 98%] 189 of 191
ERROR ~ Error executing process > 'pipeline:report (1)'

Caused by:
  Process `pipeline:report (1)` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo '[
      {
          "barcode": "barcode27",
          "type": "test_sample",
          "sample_id": "AB_103",
          "alias": "AB_103"
      },
      {
          "barcode": "barcode37",
          "type": "test_sample",
          "sample_id": "AB_115",
          "alias": "AB_115"
      },
      {
          "barcode": "barcode34",
          "type": "test_sample",
          "sample_id": "AB_110",
          "alias": "AB_110"
      },
      {
          "barcode": "barcode35",
          "type": "test_sample",
          "sample_id": "AB_113",
          "alias": "AB_113"
      },
      {
          "barcode": "barcode29",
          "type": "test_sample",
          "sample_id": "AB_105",
          "alias": "AB_105"
      },
      {
          "barcode": "barcode31",
          "type": "test_sample",
          "sample_id": "AB_107",
          "alias": "AB_107"
      },
      {
          "barcode": "barcode25",
          "type": "test_sample",
          "sample_id": "AB_101",
          "alias": "AB_101"
      },
      {
          "barcode": "barcode30",
          "type": "test_sample",
          "sample_id": "AB_106",
          "alias": "AB_106"
      },
      {
          "barcode": "barcode47",
          "type": "test_sample",
          "sample_id": "AB_125",
          "alias": "AB_125"
      },
      {
          "barcode": "barcode28",
          "type": "test_sample",
          "sample_id": "AB_104",
          "alias": "AB_104"
      },
      {
          "barcode": "barcode38",
          "type": "test_sample",
          "sample_id": "AB_116",
          "alias": "AB_116"
      },
      {
          "barcode": "barcode33",
          "type": "test_sample",
          "sample_id": "AB_109",
          "alias": "AB_109"
      },
      {
          "barcode": "barcode41",
          "type": "test_sample",
          "sample_id": "AB_119",
          "alias": "AB_119"
      },
      {
          "barcode": "barcode46",
          "type": "test_sample",
          "sample_id": "AB_124",
          "alias": "AB_124"
      },
      {
          "barcode": "barcode26",
          "type": "test_sample",
          "sample_id": "AB_102",
          "alias": "AB_102"
      },
      {
          "barcode": "barcode32",
          "type": "test_sample",
          "sample_id": "AB_108",
          "alias": "AB_108"
      },
      {
          "barcode": "barcode39",
          "type": "test_sample",
          "sample_id": "AB_117",
          "alias": "AB_117"
      },
      {
          "barcode": "barcode45",
          "type": "test_sample",
          "sample_id": "AB_123",
          "alias": "AB_123"
      },
      {
          "barcode": "barcode53",
          "type": "test_sample",
          "sample_id": "AB_131",
          "alias": "AB_131"
      },
      {
          "barcode": "barcode54",
          "type": "test_sample",
          "sample_id": "SG_101",
          "alias": "SG_101"
      },
      {
          "barcode": "barcode52",
          "type": "test_sample",
          "sample_id": "AB_130",
          "alias": "AB_130"
      },
      {
          "barcode": "barcode58",
          "type": "test_sample",
          "sample_id": "SG_105",
          "alias": "SG_105"
      },
      {
          "barcode": "barcode40",
          "type": "test_sample",
          "sample_id": "AB_118",
          "alias": "AB_118"
      },
      {
          "barcode": "barcode51",
          "type": "test_sample",
          "sample_id": "AB_129",
          "alias": "AB_129"
      },
      {
          "barcode": "barcode49",
          "type": "test_sample",
          "sample_id": "AB_127",
          "alias": "AB_127"
      },
      {
          "barcode": "barcode50",
          "type": "test_sample",
          "sample_id": "AB_128",
          "alias": "AB_128"
      },
      {
          "barcode": "barcode48",
          "type": "test_sample",
          "sample_id": "AB_126",
          "alias": "AB_126"
      },
      {
          "barcode": "barcode57",
          "type": "test_sample",
          "sample_id": "SG_104",
          "alias": "SG_104"
      },
      {
          "barcode": "barcode43",
          "type": "test_sample",
          "sample_id": "AB_121",
          "alias": "AB_121"
      },
      {
          "barcode": "barcode55",
          "type": "test_sample",
          "sample_id": "SG_102",
          "alias": "SG_102"
      },
      {
          "barcode": "barcode42",
          "type": "test_sample",
          "sample_id": "AB_120",
          "alias": "AB_120"
      },
      {
          "barcode": "barcode65",
          "type": "test_sample",
          "sample_id": "SG_112",
          "alias": "SG_112"
      },
      {
          "barcode": "barcode59",
          "type": "test_sample",
          "sample_id": "SG_106",
          "alias": "SG_106"
      },
      {
          "barcode": "barcode56",
          "type": "test_sample",
          "sample_id": "SG_103",
          "alias": "SG_103"
      },
      {
          "barcode": "barcode60",
          "type": "test_sample",
          "sample_id": "SG_107",
          "alias": "SG_107"
      },
      {
          "barcode": "barcode62",
          "type": "test_sample",
          "sample_id": "SG_109",
          "alias": "SG_109"
      },
      {
          "barcode": "barcode61",
          "type": "test_sample",
          "sample_id": "SG_108",
          "alias": "SG_108"
      },
      {
          "barcode": "barcode69",
          "type": "test_sample",
          "sample_id": "SG_116",
          "alias": "SG_116"
      },
      {
          "barcode": "barcode70",
          "type": "test_sample",
          "sample_id": "SG_117",
          "alias": "SG_117"
      },
      {
          "barcode": "barcode64",
          "type": "test_sample",
          "sample_id": "SG_111",
          "alias": "SG_111"
      },
      {
          "barcode": "barcode63",
          "type": "test_sample",
          "sample_id": "SG_110",
          "alias": "SG_110"
      },
      {
          "barcode": "barcode66",
          "type": "test_sample",
          "sample_id": "SG_113",
          "alias": "SG_113"
      },
      {
          "barcode": "barcode68",
          "type": "test_sample",
          "sample_id": "SG_115",
          "alias": "SG_115"
      },
      {
          "barcode": "barcode71",
          "type": "test_sample",
          "sample_id": "Negative",
          "alias": "Negative"
      },
      {
          "barcode": "barcode67",
          "type": "test_sample",
          "sample_id": "SG_114",
          "alias": "SG_114"
      },
      {
          "barcode": "barcode72",
          "type": "test_sample",
          "sample_id": "Positive",
          "alias": "Positive"
      }
  ]' > metadata.json
      workflow-glue report         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv           --nextclade nextclade.json         --nextclade_errors consensus.errors.csv         --revision master         --commit 98641c5bd7e14004608647086a3ebe0b73cd8822         --min_len 150         --max_len 1200         --report_depth 100         --depths depth_stats/*         --fastcat_stats per-read-stats.tsv         --bcftools_stats vcf_stats/*          --versions versions         --params params.json         --consensus_fasta consensus_fasta         --metadata metadata.json

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  --pangolin pangolin.csv
  --nextclade nextclade.json
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  /home/epi2melabs/conda/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
  [09:58:16 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/habib/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/habib/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/__init__.py", line 62, in cli
      args.func(args)
    File "/home/habib/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/report.py", line 206, in main
      epi2me_json = output_json(df, args.consensus_fasta, args.fastcat_stats)
    File "/home/habib/.nextflow/assets/epi2me-labs/wf-artic/bin/workflow_glue/report.py", line 61, in output_json
      'readcount': readcounts[entry.name],
  KeyError: 'AB_102'

Work dir:
  /home/habib/Desktop/nextflow_workspace/work/97/8759d7131fa16d562953881059a476

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

**Comment by Habibk91** [comment]
Hello again, just a quick follow-up, it turns out that some of the barcoded samples did not generate any reads, so the fastq.gz files were obviously empty. when i excluded those samples from the analysis, everything worked fine.

**Comment by Habibk91** [comment]
Hello again, just a quick follow-up, it turns out that some of the barcoded samples did not generate any reads, so the fastq.gz files were obviously empty. when i excluded those samples from the analysis, everything worked fine. So i will close this issue but keep it just in case some one else faced the same issue.

**Comment by mattdmem** [comment]
Thanks @Habibk91 - we'll add an issue to fix in the cases of no reads
