### ISSUE TITLE
Error updating Pangolin 

### ISSUE THREAD

**Issue by alexahess** [epi2me-labs/wf-artic#96]
### Operating System

Ubuntu 22.04

### Workflow Version

v0.3.31-gcb0ad4a

### Workflow Execution

Command line

### CLI command run

`nextflow run epi2me-labs/wf-artic -profile singularity --fastq data/raw/BA2/fastq_pass --sample_sheet arbeidslister/sample_sheet_BA2_fix.csv --out_dir temp_out --scheme_version ARTIC/V4.1 --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac `

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

Hello, 

I've just updated the workflow to the newest version and I get an error when it tries to update pangolin. 

The workflow works as expected when I remove from main.nf. 
```
  if [ "true" == "true" ]
  then
    pangolin --update
  fi
```

Anyone that have encountered this problem before?

### Relevant log output

```shell
executor >  local (33)
[99/c9e049] process > validate_sample_sheet                    [100%] 1 of 1 ✔
[f3/33c6f0] process > fastcat (2)                              [100%] 3 of 3 ✔
[71/62ac85] process > pipeline:getVersions                     [100%] 1 of 1 ✔
[b8/b0c1c7] process > pipeline:getParams                       [100%] 1 of 1 ✔
[0f/c926a1] process > pipeline:lookup_medaka_variant_model (1) [100%] 1 of 1 ✔
[28/a614a2] process > pipeline:runArtic (3)                    [100%] 3 of 3 ✔
[d6/170db0] process > pipeline:combineDepth                    [100%] 1 of 1 ✔
[ef/e6489a] process > pipeline:allConsensus                    [100%] 1 of 1 ✔
[e2/887b49] process > pipeline:allVariants                     [100%] 1 of 1 ✔
[04/78b839] process > pipeline:prep_nextclade                  [100%] 1 of 1 ✔
[0e/ecfda8] process > pipeline:nextclade                       [100%] 1 of 1 ✔
[95/1ec3d9] process > pipeline:pangolin                        [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:report                          -
[47/91664b] process > output (15)                              [ 94%] 17 of 18
ERROR ~ Error executing process > 'pipeline:pangolin'

Caused by:
  Process `pipeline:pangolin` terminated with an error exit status (1)

Command executed:

  if [ "true" == "true" ]
  then
    pangolin --update
  fi
  
  # set cache for snakemake to prevent permission issuses
  export XDG_CACHE_HOME=$(pwd -P)
  
  pangolin --all-versions 2>&1 | sed 's/: /,/' > pangolin.version
  pangolin --threads 4  consensus.fasta

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (78) bind mounts
  pangolin already latest release (v4.3.1)
  pangolin-data already latest release (v1.22)
  constellations already latest release (v0.1.12)
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/pangolin", line 8, in <module>
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pangolin/command.py", line 130, in main
      update.update(version_dictionary)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pangolin/utils/update.py", line 147, in update
      pip_install_dep(dependency, latest_release, data_dir)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pangolin/utils/update.py", line 76, in pip_install_dep
      subprocess.run(pip_command,
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/home/epi2melabs/conda/bin/python', '-m', 'pip', 'install', '--upgrade', 'git+https://github.com/cov-lineages/scorpio.git@v0.3.19']' returned non-zero exit status 1.
  INFO:    Cleaning up image...
```

**Comment by mattdmem** [comment]
@alexahess thanks for this report. We recently defaulted to running pangolin update at runtime to ensure users get the most up to date lineages. Will check this and get back to you.

Matt

**Comment by alexahess** [comment]
Thank you for the quick reply. 

We are currently running the workflow inside a snakemake workflow using a wrapper, if that helps you find a solution to the problem.

**Comment by mattdmem** [comment]
Thanks @alexahess - the problem is Pangolin itself implements a snakemake workflow. So you have a snakemake workflow running a nextflow workflow running a snakemake workflow 🤯

**Comment by mattdmem** [comment]
Hi @alexahess - did this fix the issue for you?

**Comment by alexahess** [comment]
Hello,

Yes, it fixed the issue. Now running pangolin separately outside the nextflow workflow so it is consistently updated.

**Comment by quedicespues** [comment]
Same error here, working smooth after adding the flag: --update_data false
